apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-gateway.fullname" . }}-secret
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.env.JWT_SECRET | b64enc }}
