apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-fastify.fullname" . }}
  labels:
    app: {{ include "api-fastify.name" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "api-fastify.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "api-fastify.name" . }}
    spec:
      containers:
        - name: {{ include "api-fastify.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: LOG_LEVEL
              value: "{{ .Values.env.LOG_LEVEL }}"
            - name: PORT
              value: "{{ .Values.env.PORT }}"
            - name: REDIS_URL
              value: "{{ .Values.env.REDIS_URL }}"
            - name: DATABASE_URL
              value: "{{ .Values.env.DATABASE_URL }}"
            - name: KAFKA_BROKERS
              value: "{{ .Values.env.KAFKA_BROKERS }}"
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
